name: Deploy

on:
  push:
    branches:
      - release
  workflow_dispatch: {}

env:
  AWS_REGION: "ap-northeast-1"
  AWS_SESSION_NAME: "bedrock-claude-chat"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ env.AWS_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy
        run: ./bin.sh --disable-self-register --bedrock-region "${{ env.AWS_REGION }}"
